database:
  enable: false
  host: localhost
  port: 3306
  user: root
  password: ''
  schema_name: Pictures
  datatable: YandeRE
yande_api:
  retry: 3
  proxies:
    http: ''
    https: ''
  headers:
    user_agent: ''
    accept: ''
    accept_language: ''
downloader:
  thread_num: 4
  max_concurrent_tasks: 3
  chunk_size: 10240
  split_size: 52428800
