services:
  picture-manager:
    image: exa160/picture-manager:${TAG:-1.0.0}
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cpus: 2
    mem_limit: 1024m
    restart: unless-stopped