database:
  enable: false
  host: 192.168.100.111
  port: 3307
  user: root
  password: Max=1616
  schema_name: Pictures
  datatable: YandeRE
yande_api:
  retry: 50
  timeout: 300
  proxy_enable: true
  proxy: http://192.168.100.222:20171
  proxies:
    http: http://192.168.100.222:20171
    https: http://192.168.100.222:20171
  headers:
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
downloader:
  thread_num: 4
  chunk_size: 10240
  split_size: 1000000
  retry: 50
  max_concurrent_tasks: 3
