"""initial schema

Revision ID: 295907d9ffe4
Revises: 
Create Date: 2026-05-16 16:23:29.210585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295907d9ffe4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='收藏夹名称'),
    sa.Column('tags', sa.Text(), nullable=True, comment='查询标签字符串'),
    sa.Column('color', sa.String(length=10), nullable=True, comment='展示颜色'),
    sa.Column('icon', sa.String(length=32), nullable=True, comment='图标标识'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序权重'),
    sa.Column('local_count', sa.Integer(), nullable=True, comment='本地图片数量'),
    sa.Column('online_count', sa.Integer(), nullable=True, comment='在线图片数量(缓存)'),
    sa.Column('last_refresh', sa.DateTime(), nullable=True, comment='最后刷新时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_local_stats',
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.Column('local_count', sa.Integer(), nullable=True, comment='本地使用次数'),
    sa.Column('last_calculated', sa.DateTime(), nullable=True, comment='最后计算时间'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('yande_artists',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='艺术家ID'),
    sa.Column('name', sa.String(length=512), nullable=False, comment='艺术家名称'),
    sa.Column('alias_id', sa.Integer(), nullable=True, comment='别名ID'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='组ID'),
    sa.Column('urls', sa.Text(), nullable=True, comment='相关链接 (JSON)'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yande_artists_name'), 'yande_artists', ['name'], unique=False)
    op.create_table('yande_data',
    sa.Column('id', sa.Integer(), nullable=False, comment='yande picture ID'),
    sa.Column('down_flag', sa.Boolean(), nullable=True, comment='yande picture down status'),
    sa.Column('tags', sa.Text(), nullable=True, comment='picture tag'),
    sa.Column('source', sa.Text(), nullable=True, comment='source url'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='yande picture create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='yande picture update time'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='yande picture update author ID'),
    sa.Column('author', sa.String(length=32), nullable=True, comment='yande picture update author name'),
    sa.Column('change', sa.Integer(), nullable=True, comment='yande picture update author ID'),
    sa.Column('score', sa.Integer(), nullable=True, comment='yande picture score'),
    sa.Column('md5', sa.String(length=32), nullable=True, comment='yande picture md5'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='yande picture file size'),
    sa.Column('file_ext', sa.String(length=6), nullable=True, comment='picture type'),
    sa.Column('file_url', sa.Text(), nullable=True, comment='down url'),
    sa.Column('is_shown_in_index', sa.Boolean(), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True, comment='preview url'),
    sa.Column('preview_width', sa.Integer(), nullable=True),
    sa.Column('preview_height', sa.Integer(), nullable=True),
    sa.Column('actual_preview_width', sa.Integer(), nullable=True),
    sa.Column('actual_preview_height', sa.Integer(), nullable=True),
    sa.Column('sample_url', sa.Text(), nullable=True, comment='sample url'),
    sa.Column('sample_width', sa.Integer(), nullable=True),
    sa.Column('sample_height', sa.Integer(), nullable=True),
    sa.Column('sample_file_size', sa.Integer(), nullable=True),
    sa.Column('jpeg_url', sa.Text(), nullable=True, comment='jpeg url'),
    sa.Column('jpeg_width', sa.Integer(), nullable=True),
    sa.Column('jpeg_height', sa.Integer(), nullable=True),
    sa.Column('jpeg_file_size', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Enum('s', 'q', 'e', name='rating'), nullable=True, comment='图片评级'),
    sa.Column('is_rating_locked', sa.Boolean(), nullable=True),
    sa.Column('has_children', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_held', sa.Boolean(), nullable=True),
    sa.Column('frames_pending_string', sa.Text(), nullable=True),
    sa.Column('frames_pending', sa.JSON(), nullable=True),
    sa.Column('frames_string', sa.Text(), nullable=True),
    sa.Column('frames', sa.JSON(), nullable=True),
    sa.Column('is_note_locked', sa.Boolean(), nullable=True),
    sa.Column('last_noted_at', sa.Integer(), nullable=True),
    sa.Column('last_commented_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yande_data_down_flag'), 'yande_data', ['down_flag'], unique=False)
    op.create_index(op.f('ix_yande_data_rating'), 'yande_data', ['rating'], unique=False)
    op.create_table('yande_tags',
    sa.Column('id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.Column('name', sa.String(length=512), nullable=False, comment='标签名称'),
    sa.Column('count', sa.Integer(), nullable=True, comment='使用数量'),
    sa.Column('type', sa.Integer(), nullable=True, comment='类型: 0=general, 1=artist, 3=copyright, 4=character'),
    sa.Column('ambiguous', sa.Boolean(), nullable=True, comment='有争议'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yande_tags')
    op.drop_index(op.f('ix_yande_data_rating'), table_name='yande_data')
    op.drop_index(op.f('ix_yande_data_down_flag'), table_name='yande_data')
    op.drop_table('yande_data')
    op.drop_index(op.f('ix_yande_artists_name'), table_name='yande_artists')
    op.drop_table('yande_artists')
    op.drop_table('tag_local_stats')
    op.drop_table('favorite_folders')
    # ### end Alembic commands ###
