"""add download_task table

Revision ID: 4bfd907595ea
Revises: 295907d9ffe4
Create Date: 2026-05-16 16:29:07.395255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfd907595ea'
down_revision: Union[str, None] = '295907d9ffe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_task',
    sa.Column('task_id', sa.String(length=36), nullable=False, comment='任务ID'),
    sa.Column('image_id', sa.Integer(), nullable=True, comment='图片ID'),
    sa.Column('file_name', sa.String(length=256), nullable=True, comment='文件名'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='总大小'),
    sa.Column('status', sa.Enum('pending', 'downloading', 'paused', 'completed', 'failed', 'cancelled', name='taskstatus'), nullable=True, comment='任务状态'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='进度(0-100)'),
    sa.Column('downloaded_size', sa.Integer(), nullable=True, comment='已下载大小'),
    sa.Column('speed', sa.Integer(), nullable=True, comment='下载速度'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_download_task_image_id'), 'download_task', ['image_id'], unique=False)
    op.create_index(op.f('ix_download_task_status'), 'download_task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_task_status'), table_name='download_task')
    op.drop_index(op.f('ix_download_task_image_id'), table_name='download_task')
    op.drop_table('download_task')
    # ### end Alembic commands ###
